# Generated by Django 5.0.4 on 2024-08-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_gender_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
